version: "3.9"
services:

  # MONGODB
  mongodb:
    image: mongo:4.2
    container_name: drakcar-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - ${DATA_PATH_HOST}/mongodb:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017

  # MONGODB-EXPRESS
  mongo-express:
    image: mongo-express:0.54.0
    container_name: drakcar-mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    expose:
      - 8081

  # API
  api:
    image: node:14-alpine
    container_name: drakcar-api
    privileged: true
    env_file:
      - .env
    volumes:
      - ${DATA_PATH_HOST}/docker/certs:/certs
      - ../backend:/app
    working_dir: /app
    command: sh -c "npm ci && npm run start:debug:docker"
    depends_on:
      - mongodb
    tmpfs: /tmp
    ports:
      - 9229:9229

  # WEB
  web:
    image: node:14-alpine
    container_name: drakcar-web
    privileged: true
    env_file:
      - .env
    volumes:
      - ${DATA_PATH_HOST}/docker/certs:/certs
      - ../web:/app
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    depends_on:
      - api
    tmpfs: /tmp
    ports:
      - 3000:3000
  
  # KEYCLOAK
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    command: -b 0.0.0.0
    container_name: drakcar-keycloak
    env_file:
      - .env
    environment:
      DB_VENDOR: ${KEYCLOAK_DB_VENDOR}
      DB_ADDR: ${KEYCLOAK_DB_ADDR}
      DB_PORT: 5432
      DB_NAME: ${KEYCLOAK_DB_NAME}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASS}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    # volumes:
    #   - ${CONFIG_PATH_HOST}/keycloak/starter-theme:/opt/jboss/keycloak/themes/starter
    #   - ${CONFIG_PATH_HOST}/keycloak/initial-config:/opt/jboss/keycloak/config
    #   - ${CONFIG_PATH_HOST}/keycloak/startup:/opt/jboss/startup-scripts
    ports:
      - 8080:8080
    depends_on:
      - postgres

  # POSTGRES
  postgres:
    image: postgres:9.6
    user: postgres
    privileged: true
    container_name: drakcar-postgres
    env_file:
      - .env
    volumes:
      - ${CONFIG_PATH_HOST}/postgres:/docker-entrypoint-initdb.d/
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_DB_NAME=${KEYCLOAK_DB_NAME}
      - KEYCLOAK_DB_USER=${KEYCLOAK_DB_USER}
      - KEYCLOAK_DB_PASS=${KEYCLOAK_DB_PASS}

  # PGADMIN
  pgadmin:
    env_file:
      - .env
    container_name: drakcar-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    expose:
      - 80
    volumes:
      - ${CONFIG_PATH_HOST}/pgadmin/servers.json:/pgadmin4/servers.json